#!/bin/sh

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		exit 1
	else
		if [ "$remote_sha" = $z40 ]
		then
			range="$local_sha"
		else
			range="$remote_sha..$local_sha"
		fi

		gulp test
		if [ "$?" -ne 0 ]
		then
			echo "Tests fails in $local_ref, not pushing"
			exit 1
		fi
	fi
done

exit 0
