export const SQSTypes = Object.freeze({
  notification: 'notificationSQSUrl',
  emailNotification: 'emailNotificationSQSUrl',
  activation: 'activationSQSUrl',
  workflow: 'workflowSQSUrl',
  recharge: 'rechargeSQSUrl',
  payment: 'paymentSQSUrl',
  crm: 'crmSQSUrl',
  portal: 'portalSQSUrl',
  shopify: 'shopifySQSUrl',
  thirdParty: 'thirdPartySQSUrl',
  hubspot: 'hubspotSQSUrl',
  simPurchase: 'simPurchaseSQSUrl',
  accountPlanUpdate: 'planUpdateSQSUrl',
  billingInvoice: 'billingInvoiceSQSUrl',
  invoicePdf: 'invoicePdfSQSUrl',
  commission: 'commissionSQSUrl',
  eCommerce: 'ecommerceSQSUrl',
  eCommerceRecharge: 'eCommerceRechargeSQSUrl',
});
