export const ContactProperties = ['firstname', 'lastname', 'email', 'phone', 'address', 'address2', 'city', 'state', 'country', 'zip'];

export const DealProperties = [
  'destination',
  'dealname',
  'plan',
  'airtime',
  'plan_start_date',
  'delivery_type',
  'sim_validity',
  'sim_validity_date',
  'collection_points',
  'phone_compatible',
  'amount',
  'pipeline',
  'dealstage',
  'sim_type',
  'plan_expire_date',
  'payment_status',
  'payment_link',
  'paid_at',
  'due_date',
  'invoice',
  'delivery_address',
];

export const SimProperties = [
  'sim_validity',
  'sim_type',
  'sim_serial_number',
  'email',
  'activation_code',
  'smdp_address',
  'airtime',
  'plan',
  'mobile_number',
  'mcc_country',
  'qr_code',
  'sim_number',
  'sim_status',
  'sim_expire_date',
  'validity',
  'plan_expire_date',
  'sim_name',
];
